### ISSUE TITLE
Notification issue

### ISSUE THREAD

**Issue by random-tester-nuked** [zacharee/SamloaderKotlin#1]
Hi thanks for your amazing work,
I've found a little issue (I'm on Samsung S10+ wirh last firmware android 11 one ui 3.1)

So when the firmware aren't available to download one notification stuck at same point eternally

![Screenshot_20210301-214854_Samsung Firmware Downloader](https://user-images.githubusercontent.com/67654563/109557821-e3e6a400-7ad8-11eb-92b1-9f355581b385.jpg)
![Screenshot_20210301-215319_Samsung Internet](https://user-images.githubusercontent.com/67654563/109557838-e812c180-7ad8-11eb-9054-89b1314a408f.jpg)

**Comment by zacharee** [comment]
The notification will stay as long as the app is running.

**Comment by random-tester-nuked** [comment]
Oh ok thnx but even if I close the apps from recent apps the notifications are still here

**Comment by random-tester-nuked** [comment]
Thanks you for all

**Comment by zacharee** [comment]
https://github.com/zacharee/SamloaderKotlin/releases/tag/0.2.1
