### ISSUE TITLE
AVs detect Bifrost as a trojan

### ISSUE THREAD

**Issue by andrive-one8** [zacharee/SamloaderKotlin#100]
Antiviruses give a false positive because it shares a similar name with an older virus called Bifrose

[Malwarebytes](https://github-production-user-asset-6210df.s3.amazonaws.com/75690662/244974492-a655e212-a643-4bc1-af39-7380b7474449.jpg)

**Comment by parkerlreed** [comment]
This is already mentioned in the Readme

https://github.com/zacharee/SamloaderKotlin#why-is-my-antivirus-flagging-the-app
