### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by MSBBZBL** [zacharee/SamloaderKotlin#101]
Any download does not work anymore

![image](https://github.com/zacharee/SamloaderKotlin/assets/79850630/4e1fca47-d1b8-49bd-a6b6-3fe0b1676d20)

**Comment by shuffleznl** [comment]
Same for me, with SM-S901B EUX. Not sure the StaticLoggerBinder is issue/cause though.

**Comment by zacharee** [comment]
The SLF4J error isn't related. Samsung isn't serving EUX firmware for the S22 series for some reason.
