### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by TaylorGit32** [zacharee/SamloaderKotlin#103]
No matter what CSC i choose. I get a access denied error
Running on Windows 10 22H2
Attemtping to get Samsung Galaxy S22 Firmware (SM-S901B) EUX

**Comment by update-freak** [comment]
same for me: download for the current version of SM-S911B EUX does not work

**Comment by tadekdudek** [comment]
Same problem, SM-J327A, CSC is ATT

**Comment by update-freak** [comment]
I checked with 1.15.1.
I had the same issue:

![bifrost](https://github.com/zacharee/SamloaderKotlin/assets/40196995/09c1e1e1-9df5-4b3f-b4ca-02c026e56323)

**Comment by zacharee** [comment]
https://github.com/zacharee/SamloaderKotlin/issues/116

**Comment by qtqgyt** [comment]
Samsung tab a7 lite, samsung tab a8, samsung tab a9, all cscs.
