### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by geekmaster21** [zacharee/SamloaderKotlin#108]
When i try to download a firmware whatever it is i got this error : SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details. And in fact the app fail crc check everytimes

**Comment by jcpirate76** [comment]
I'm getting the exact same error message. Can't locate or download any firmware versions for SM-N975U

**Comment by zacharee** [comment]
The SLF4J error isn't something that matters. The real error was masked and has been fixed.
