### ISSUE TITLE
Pause button

### ISSUE THREAD

**Issue by abiud254** [zacharee/SamloaderKotlin#11]
The resume feature is _alright_ but i don't trust files that stopped downloading because of an error; something always tells me they're _corrupted_ so I don't think a pause button would hurt anyone. I would love to tell you not to change a thing because it's amazing but I kinda need that pause button. But **overall** it's very **awesome** and would recommend it to any other firmware source out there. **Keep up the good work.**

**Comment by zacharee** [comment]
The files are downloaded sequentially one byte at a time. Unless something goes really wrong on the operating system end, it shouldn't be possible to have corruption. The pause button would effectively be the same as closing the program.

**Comment by abiud254** [comment]
Thanks for the reply. I actually tried turning off the pc then resuming the download by reopening the program..still worked and I actually used the file and it wasn't corrupted. Nice program.
