### ISSUE TITLE
CRC failed always

### ISSUE THREAD

**Issue by nemenos** [zacharee/SamloaderKotlin#110]
I've tried 2 different models, many CSC. Always same problem. It seems it downloads very few bytes and fails.
Tried both android and windows version.
Any suggestions?
Thanks in advance

**Comment by Groonir** [comment]
Also have  the same problem

**Comment by evdcush** [comment]
Same problem.

**Comment by Tostis** [comment]
The application is reporting wrong error. It's a HTTP 403 Forbidden. Seems that the FUS client cannot authenticate to Samsung servers. You can seet response in tk.zwander.common.tools.FusClientKt#doDownloadFile.

**Comment by Tostis** [comment]
Same as #107

**Comment by zacharee** [comment]
Fixed.
