### ISSUE TITLE
"Bad return status: 400" for  SM-S908B region EUX

### ISSUE THREAD

**Issue by divinity76** [zacharee/SamloaderKotlin#111]
trying to download SM-S908B with EUX results in
> Bad return status: 400

SM-S908B with EUX definitely exist, here is a screenshot as proof:

![](https://stuff.ratma.net/2023/Screenshot_20231023_002541_Settings.jpg)
and here is a screenshot of trying to download it with Bifrost:
![image](https://github.com/zacharee/SamloaderKotlin/assets/1874996/3a00e66d-d8f3-4f15-a577-e82c9a69d0ac)

interestingly, same happens with EUY but /not/ with BTE (BTE works fine).

**Comment by Xpl0itR** [comment]
same

**Comment by divinity76** [comment]
@Xpl0itR until this is resolved, i wrote a region scanner to find alternative regions at https://github.com/jesec/SamFirm.NET/issues/3

```
$ time php test2.php SM-F916N
total urls to check per model string: 509
total urls to check: 2545
Checking model string 1/5: SM-F916N
http://fota-cloud-dn.ospserver.net/firmware/KTC/SM-F916N/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/LUC/SM-F916N/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/SKC/SM-F916N/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/KOO/SM-F916N/version.xml   : 200
(...)
```
- in my case I couldn't download the correct EUX-region firmware, but my scanner found a compatible region BTE which worked fine
![image](https://github.com/zacharee/SamloaderKotlin/assets/1874996/e3dddfb0-b922-4e0b-9a25-24c5ec87c58d)

**Comment by divinity76** [comment]
@MichaelDavidGK because my phone's model code is `SM-S908BZWGEUB` , but the update server did not use my full model code, and I wasn't sure exactly what model code the update servers used, so after an exhaustive search,
```
hans@cac3:~$ time php test2.php SM-S908BZWGEUB
total urls to check per model string: 509
total urls to check: 5599
Checking model string 1/11: SM-S908BZWGEUB
Checking model string 2/11: SM-S908BZWGEU
Checking model string 3/11: SM-S908BZWGE
Checking model string 4/11: SM-S908BZWG
Checking model string 5/11: SM-S908BZW
Checking model string 6/11: SM-S908BZ
Checking model string 7/11: SM-S908B
http://fota-cloud-dn.ospserver.net/firmware/AFG/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/MOB/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/VIP/SM-S908B/version.xml   : 200
http://fota-cloud-dn.ospserver.net/firmware/O2C/SM-S908B/version.xml   : 200
(...)
```
- it turns out that the update server used the model code `SM-S908B` even though the Samsung warranty page use the model code `SM-S908BZWGEUB`
![image](https://github.com/zacharee/SamloaderKotlin/assets/1874996/fb7314e5-233f-4c6e-8fa3-8dd70c0f7f56)


> also even if it exists it's a different model, so there is no point to it

I certainly hope not (and the SM-S908B firmware was fully compatible with my SM-S908BZWGEUB model.)

**Comment by zacharee** [comment]
There isn't really much I can do if Samsung isn't serving the firmware for a certain CSC directly. As suggested above, you'll have to try a different CSC that contains yours.

**Comment by divinity76** [comment]
@zacharee problem is, the Samsung phone itself can download  SM-S908B region EUX, but not Bifrost - The phone is doing /something/ differently, and the server is reacting to it

**Comment by zacharee** [comment]
OTA packages use a different server and require a pretty complex registration process that's unique per-device.

**Comment by divinity76** [comment]
@zacharee oh ok. close this issue then?

Btw would be nice if Bifrost itself could get a region scanner (I don't do Kotlin myself, but I wrote one in PHP to get around the  SM-S908B+EUX issue - would have saved me the trouble if Bifrost had one)

**Comment by zacharee** [comment]
Can you request that in a new issue so I can track it better?

**Comment by MK73DS** [comment]
I experience the same problem with Bifrost 1.19.3 when trying to download S928BXXS3AXI1/S928BOXM3AXI1/S928BXXS3AXI1/S928BXXS3AXI1 for SM-S928B and EUX CSC. The update definitely exists, I got an OTA notification for it and it is present in samfw https://samfw.com/firmware/SM-S928B/EUX/S928BXXS3AXI1
![image](https://github.com/user-attachments/assets/2a4966d9-8d18-425e-b568-217cdabe1644)
