### ISSUE TITLE
Galaxy watch 4 R870

### ISSUE THREAD

**Issue by 7716508** [zacharee/SamloaderKotlin#114]
I tried to download a flash file for galaxy watch 4 SM-R870 ILO and I get a error 400, I tried a few different region and they are all the same error.
![Screenshot_20231109_152127_Bifrost](https://github.com/zacharee/SamloaderKotlin/assets/74883610/543b435b-58fa-4e2a-a44a-07458020ed37)

**Comment by zacharee** [comment]
Unfortunately you can't download the firmware for watches directly.
