### ISSUE TITLE
I am unable to download the following model: SC51Aa

### ISSUE THREAD

**Issue by jianfei96** [zacharee/SamloaderKotlin#115]
This is an actual existing model.
Samsung's website.: https://doc.samsungmobile.com/SC51Aa/DCM/doc.html

Could this be due to the tool automatically converting lowercase letters to uppercase?
Note: I want to download SC51Aa, not SC-51A.(Yes, I can download SC-51A)
SC51Aa
![image](https://github.com/zacharee/SamloaderKotlin/assets/18232033/b2f64e93-18e5-45e8-9168-6312b77212b1)
SC-51A
![image](https://github.com/zacharee/SamloaderKotlin/assets/18232033/99243684-1118-4ae2-b0e4-8c416cb7fc11)

**Comment by zacharee** [comment]
The next version will have an option to allow lowercase letters, but it looks like Samsung isn't serving this firmware anyway: 
<img width="912" alt="image" src="https://github.com/zacharee/SamloaderKotlin/assets/9020352/6b64660c-63ab-4dba-91e1-04f3553c7732">

**Comment by zacharee** [comment]
1.15.0 has the option (click the settings gear in the bottom right) to allow lowercase characters.

**Comment by jianfei96** [comment]
> The next version will have an option to allow lowercase letters, but it looks like Samsung isn't serving this firmware anyway: <img alt="image" width="912" src="https://user-images.githubusercontent.com/9020352/282221343-6b64660c-63ab-4dba-91e1-04f3553c7732.png">

Thanks.
I downloaded it use this tool, with the command "SamFirm.exe -model SC51Aa -region DCM".
https://github.com/ivanmeler/SamFirm_Reborn

So I think it exists.

**Comment by zacharee** [comment]
OK, I think this should be fixed in 1.15.1.

For some reason, the firmware needs to be passed all-uppercase to Samsung's servers when requesting the file, even though it has lowercase characters.

**Comment by jianfei96** [comment]
> OK, I think this should be fixed in 1.15.1.
> 
> For some reason, the firmware needs to be passed all-uppercase to Samsung's servers when requesting the file, even though it has lowercase characters.

That's great news, thank you for your efforts in development.
