### ISSUE TITLE
unable to download any firmware

### ISSUE THREAD

**Issue by kdejeqq** [zacharee/SamloaderKotlin#117]
I tried to download the firmware for my Samsung Galaxy S9+ SM-G965F and I still get a response error from the FUS server. This happens for any firmware. Below are the logs from SamFirm :

SamFirm v1.4.2
Checking firmware for SM-G965F/XEF/G965FXXUHFVG4/G965FOXMHFVB4/G965FXXUHFVB4/G965FXXUHFVG4
Error UpdateCheck(): Could not send BinaryInform. Status code (200/401)
Error CheckHtmlXmlStatus(): Authorization failed.
Checking firmware for SM-G965F/XEF/G965FXXSDFTL1/G965FOXMDFTL1/G965FXXSDFTL1/G965FXXSDFTL1
Error UpdateCheck(): Could not send BinaryInform. Status code (200/401)
Error CheckHtmlXmlStatus(): Authorization failed.
Error UpdateCheckAuto(): Could not fetch info for SM-G965F/XEF. Please check the input data.

I also took a screenshot :
<img width="557" alt="Capture" src="https://github.com/zacharee/SamloaderKotlin/assets/66625937/e4c9d695-f43c-4494-874c-effec1332aed">

**Comment by zacharee** [comment]
This repo is for Bifrost, not SamFirm.
