### ISSUE TITLE
No ARM64 macOS Native Build?

### ISSUE THREAD

**Issue by ThePhoenix576** [zacharee/SamloaderKotlin#119]
I saw on the changelog that there is supposed to be an ARM64 Native macOS build. but the pre-built macOS App is an Intel only build

<img width="812" alt="image" src="https://github.com/zacharee/SamloaderKotlin/assets/40349017/239c4d56-942e-481e-a3fc-9afda9064191">

**Comment by zacharee** [comment]
It looked like GitHub had added a small runner for macOS ARM64, but it still isn't available. Native ARM64 builds will be available as soon as GitHub adds that runner.

**Comment by ThePhoenix576** [comment]
> It looked like GitHub had added a small runner for macOS ARM64, but it still isn't available. Native ARM64 builds will be available as soon as GitHub adds that runner.

Ah I see. That's fine :) I was just wondering since I thought it's a bug or something. Thanks for checking it!
