### ISSUE TITLE
Download Speed Issue

### ISSUE THREAD

**Issue by PitchAbyss** [zacharee/SamloaderKotlin#120]
when I start to download the speed goes full as per my internet speed plan but soon it drops drastically

like it started at 75-80 Mbps and dropped to 4-5-6 Mbps soon

![image](https://github.com/zacharee/SamloaderKotlin/assets/13099434/8e24f164-5caa-47d8-b605-b36f7db5b62d)

**Comment by zacharee** [comment]
Samsung will sometimes throttle download speeds. There isn't anything I can do about it, unfortunately.

**Comment by PitchAbyss** [comment]
> Samsung will sometimes throttle download speeds. There isn't anything I can do about it, unfortunately.

Pathetic samsung service...thanks man i hope there was a fix
