### ISSUE TITLE
Feature Request - Make Bifrost Accessible From Command Line

### ISSUE THREAD

**Issue by TheRealMrWicked** [zacharee/SamloaderKotlin#121]
I have been trying to fully automate the process of downloading the Samsung firmware, I would like to know if it is possible to run this program from the command line in a batch file.

I previously used Samloader for this purpose but it is dead now, if anyone has any alternative suggestions please tell me.

I fully understand if the dev doesn't want to implement this feature.

Thank you in advance.

- MrWicked

**Comment by zacharee** [comment]
There's a fork of Samloader that fixes the download error https://github.com/martinetd/samloader

**Comment by TheRealMrWicked** [comment]
Thank you so much Zachary, I appreciate the help with the issue.
