### ISSUE TITLE
Bad return status 408

### ISSUE THREAD

**Issue by update-freak** [zacharee/SamloaderKotlin#132]
**Describe the bug**
When I try to download the Firmware for SM-A520F with DBT I got the error "Bad return status: 408"
Link: https://www.sammobile.com/samsung/galaxy-s7/firmware/SM-A520F/DBT/

**To Reproduce**
1. Insert  SM-A520F, DBT
2. Click on 'Check for Updates' and then 'Download'

**Expected behavior**
Download should work

**Screenshots**
![2023-12-31 09_34_34-Bifrost](https://github.com/zacharee/SamloaderKotlin/assets/40196995/64a96556-e1d3-4e64-8042-f8e7da4c68ec)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Bifrost version: 1.16.10

**Comment by Martyn911** [comment]
Use the service https://samfirm.shop/search/SM-A520F+DBT

**Comment by Fede2782** [comment]
You need the IMEI as described in the README. But it is a very old model and Samsung may also stopped serving the fw for that device

**Comment by update-freak** [comment]
Ah, sry I forgot the IMEI.
Now it works.
Thanks for the quick response.
