### ISSUE TITLE
Program runs with GUI without text.

### ISSUE THREAD

**Issue by somerandom907** [zacharee/SamloaderKotlin#137]
**Describe the bug**
When I run the program it runs the GUI with no text, no errors in the command prompt. It used to before but after reinstalling windows 10 it doesn't.

**To Reproduce**
1. Go to 'bifrost-1.16.14-windows-amd64\bin\'
2. Click on 'Bifrost.exe'

**Expected behavior**
GUI is supposed to show with text on textboxes, buttons etc.

**Screenshots**
![image](https://github.com/zacharee/SamloaderKotlin/assets/157152820/7a3e6222-64ba-488b-80ff-ebf57af812af)

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 19045
 - Graphics Card: ATI Mobility Radeon HD 4650
 - Processor: Intel Core2 Duo T6400

**Comment by zacharee** [comment]
Does this work? https://github.com/zacharee/SamloaderKotlin/releases/tag/1.16.15-test

**Comment by somerandom907** [comment]
Unfortunately it doesn't.
![image](https://github.com/zacharee/SamloaderKotlin/assets/157152820/2e59f8eb-7206-4dca-9bb3-32298a2e71e3)

**Comment by zacharee** [comment]
Do you have the ATI drivers installed?

**Comment by somerandom907** [comment]
> Do you have the ATI drivers installed?
Yes I do.
![image](https://github.com/zacharee/SamloaderKotlin/assets/157152820/eb7b02aa-f782-4d62-b7f1-5e02bbb1eab0)

**Comment by zacharee** [comment]
Does 1.16.3 work or are all versions not rendering text?

**Comment by somerandom907** [comment]
> Does 1.16.3 work or are all versions not rendering text?

If i remember correctly, a few months ago (probably September, October maybe even before) the text was fine it worked. But from like November-December it doesn't. I didn't report it because i thought someone will catch it.
The text is still gone on 1.16.3

![image](https://github.com/zacharee/SamloaderKotlin/assets/157152820/8a5506d7-4292-4dfd-b6bf-c0fb097cf1e8)

**Comment by zacharee** [comment]
Is there a version that does work?

**Comment by somerandom907** [comment]
Well comparing the upload dates of the releases, versions 1.13 worked. But when I tried it, it didn't.
I also tried 1.12 for good measure, it also didn't work.

**Comment by zacharee** [comment]
The error isn't related. It's just a warning that's fixed in later versions. I think something is broken with your installation, but I don't know what it could be.

**Comment by zacharee** [comment]
Actually, are you keeping the folder structure when you extract the ZIP? `Bifrost.exe` should be inside a `bin` folder.

**Comment by somerandom907** [comment]
> Actually, are you keeping the folder structure when you extract the ZIP? `Bifrost.exe` should be inside a `bin` folder.

In newer versions yes the exe is in a 'bin' folder, in older ones the exe is in the Bifrost folder.

**Comment by somerandom907** [comment]
Should I just reinstall windows?

**Comment by zacharee** [comment]
I think you might need to.

**Comment by somerandom907** [comment]
Well, I guess there is nothing left to do except that. I'll inform you on if it's working.

**Comment by somerandom907** [comment]
So, I reinstalled Windows and it still doesn't work.
![image](https://github.com/zacharee/SamloaderKotlin/assets/157152820/5a8a673a-ad24-4f0c-b105-1827eb47cecb)

**Comment by zacharee** [comment]
I'm curious if there is actually text, but the color is the same as the background for some reason. If you type something in one of the text fields and select it, can you then see the text?

**Comment by somerandom907** [comment]
> I'm curious if there is actually text, but the color is the same as the background for some reason. If you type something in one of the text fields and select it, can you then see the text?

No, I cannot.

![image](https://github.com/zacharee/SamloaderKotlin/assets/157152820/6c4ff933-c1d1-4a8a-89be-bb5b09637eae)

**Comment by zacharee** [comment]
Can you try this test release? It's forcing Arial to be used instead of looking for Segoe UI.

https://github.com/zacharee/SamloaderKotlin/releases/tag/1.17.2-font-test

**Comment by somerandom907** [comment]
> Can you try this test release? It's forcing Arial to be used instead of looking for Segoe UI.
> 
> https://github.com/zacharee/SamloaderKotlin/releases/tag/1.17.2-font-test

Still nothing
![3](https://github.com/zacharee/SamloaderKotlin/assets/157152820/1c50e015-2a00-4744-9a22-05c47f7f49cb)
![4](https://github.com/zacharee/SamloaderKotlin/assets/157152820/a17eea77-fe9a-4eca-97ff-cc077cee1771)

**Comment by zacharee** [comment]
How about this https://github.com/zacharee/SamloaderKotlin/releases/tag/1.17.2-software-render

**Comment by zacharee** [comment]
Interesting. That means something is wrong with OpenGL on your machine. What version of the graphics drivers do you have installed?

**Comment by somerandom907** [comment]
![image](https://github.com/zacharee/SamloaderKotlin/assets/157152820/92a365a5-70b5-48da-b529-04d998bfdc5a)

**Comment by somerandom907** [comment]
This is the latest official driver for my graphics card. There is a beta 13.4 driver but i don't trust beta drivers.

**Comment by somerandom907** [comment]
![image](https://github.com/zacharee/SamloaderKotlin/assets/157152820/720856ee-cc0c-4771-b760-250d6222dcfc)

**Comment by somerandom907** [comment]
Yes, the driver is for Win 8 because drivers for Windows 10 doesn't exist. But i used it before and i didn't have any problems like this.

**Comment by somerandom907** [comment]
Should I test the beta driver?

**Comment by zacharee** [comment]
It looks like the Windows Update Catalog has much newer drivers than what's listed on AMD's website. I'd try letting Windows Update install device drivers. Or you could grab the CAB manually: https://catalog.s.download.windowsupdate.com/c/msdownload/update/driver/drvs/2021/05/display_daf38d1d675861a23a5e5bd3ae052a1d51751ea6.cab.

**Comment by somerandom907** [comment]
> It looks like the Windows Update Catalog has much newer drivers than what's listed on AMD's website. I'd try letting Windows Update install device drivers. Or you could grab the CAB manually: https://catalog.s.download.windowsupdate.com/c/msdownload/update/driver/drvs/2021/05/display_daf38d1d675861a23a5e5bd3ae052a1d51751ea6.cab.

Okay, I will try, but I don't really trust them.

**Comment by somerandom907** [comment]
![image](https://github.com/zacharee/SamloaderKotlin/assets/157152820/7a450f54-1e04-4b43-a4b5-3fa1634ceb91)
The driver doesn't work. It's incompatible.

**Comment by somerandom907** [comment]
I'll test the beta driver.

**Comment by zacharee** [comment]
What version of Windows 10 are you running? That package should work on 1903 and later, which is pretty old.

**Comment by somerandom907** [comment]
> What version of Windows 10 are you running? That package should work on 1903 and later, which is pretty old.
> 
> There's also this driver from 2015 https://catalog.s.download.windowsupdate.com/d/msdownload/update/driver/drvs/2016/02/20813855_87923c8bb67e2128747f97506937420fe3835e06.cab.

Windows 10 22H2

**Comment by somerandom907** [comment]
How do I install this driver, the .cab file is full of .inf and .cat files?

**Comment by zacharee** [comment]
Right click the .inf files and choose "Install".

**Comment by somerandom907** [comment]
Okay, thank you.

**Comment by somerandom907** [comment]
I did it, nothing happened, just a bunch of messages that inform me that the files are installed.

**Comment by zacharee** [comment]
Open Device Manager now and check for driver updates on your GPU there.

Zachary Wander

**Comment by somerandom907** [comment]
> Open Device Manager now and check for driver updates on your GPU there. Zachary Wander
> […](#)
> On Jan 22, 2024 at 5:02 PM -0500, somerandom907 ***@***.***>, wrote: I did it, nothing happened, just a bunch of messages that inform me that the files are installed. — Reply to this email directly, view it on GitHub or unsubscribe. You are receiving this email because you commented on the thread. Triage notifications on the go with GitHub Mobile for iOS or Android.

I was checking the whole time i was installing, nothing. I reloaded it, after installing it, still nothing, just Microsoft Basic Display Adapter.

**Comment by zacharee** [comment]
Alright, I’m not sure what’s up with the drivers, but I’m going to be releasing a new version that should hopefully step through rendering engines until it finds a good one.

Zachary Wander
