### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by kuragna** [zacharee/SamloaderKotlin#14]
I can't download firmware.
![Screenshot_20210504-203009](https://user-images.githubusercontent.com/83675476/117075077-c1b11280-ad23-11eb-81a7-611bd38e4089.jpg)

**Comment by zacharee** [comment]
It works fine for me.
![Screenshot_20210504-175939_Samsung Firmware Downloader](https://user-images.githubusercontent.com/9020352/117075329-9ff36380-ad02-11eb-9c22-b96d0cd89740.jpg)

**Comment by kuragna** [comment]
it's working now, after allow access to download folder.
![Screenshot_20210504-221858](https://user-images.githubusercontent.com/83675476/117077267-4f423180-ad27-11eb-989e-56497dfda05a.jpg)

Thanks.
