### ISSUE TITLE
Cannot fetch Galaxy Watch 4 Classic Firmware

### ISSUE THREAD

**Issue by techyminati** [zacharee/SamloaderKotlin#152]
**Describe the bug**
* The tool cannot fetch Galaxy Watch 4 fw

**To Reproduce**
1. Go to device model  Set it to- SM-R890
2. Click on Check Updates
3. Update is found, click on download, it doesnt work and throws error 408, when I give correct serial number it throws error 400

**Expected behavior**
Firmware should be downloaded

**Screenshots**
![image](https://github.com/zacharee/SamloaderKotlin/assets/63485082/72b4a80c-8a35-4e43-a916-6b0124740920)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Browser: Chrome
 - Version 1.17.5

**Additional context**
Nothing  much

**Comment by zacharee** [comment]
Samsung doesn't serve full firmware for watches.

**Comment by techyminati** [comment]
@zacharee it does, I'm getting a 1.7GB OTA from Watch 4 Manager

**Comment by zacharee** [comment]
The OTA system is completely separate from the system Bifrost uses, and hasn't been successfully reverse engineered yet.

**Comment by techyminati** [comment]
Ah okay, anything we can expect or not?

**Comment by zacharee** [comment]
Probably not. The system is very complex and seems to depend on generating unique keys based on the secure element in the device to register it.

**Comment by techyminati** [comment]
@zacharee I managed to grab ota link via packet capture, but it says it requires a key value pair

**Comment by techyminati** [comment]
@zacharee what could be case where link says "Access Denied"?

**Comment by techyminati** [comment]
[URL](https://fota-s3-dn.ospserver.net/firmware/INS/SM-R890/4f191755ab53410a90a1b12b76e6f083.bin?px-hash=&px-wid=2777391-WCC240210073551&px-wctime=2024-02-10%2007:35:51&px-cc=INS&px-mn=SM-R890&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHA6Ly9mb3RhLXMzLWRuLm9zcHNlcnZlci5uZXQvZmlybXdhcmUvSU5TL1NNLVI4OTAvNGYxOTE3NTVhYjUzNDEwYTkwYTFiMTJiNzZlNmYwODMuYmluP3B4LWhhc2g9JnB4LXdpZD0yNzc3MzkxLVdDQzI0MDIxMDA3MzU1MSZweC13Y3RpbWU9MjAyNC0wMi0xMCUyMDA3OjM1OjUxJnB4LWNjPUlOUyZweC1tbj1TTS1SODkwKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcxMTAwNjU1NX19fV19&Signature=YUg88rNXIdvkiNrHWu9kE42xcMHDDIgsu~SKlMTJKOFn3Mre9c~2KAjGvu-OoMXfPple8-fD71e73C~ntJbzcCllBkAApHcXBvyQxnZb0tgTsTdvrdzDtHyCbyJfnp4CwznLu5nvyOZha0ewrA4MNhwFpEYwAiyHz5VCfNTHlG-SwHOEsOl4MOoJdUoHREpr99kUfnq96N4ZO5D4F3FvTw2nTi6iQgxmCpBN1eiA8eei1WwTj3iFSArSeRedLQ20ZCuZW8ycr5glGNMldh4pvxlrIUvgg7bngNSCmiCcRIhM8yGaHHp-mdni-ayYDsRIYR86i9FmcClEZIZKVmEWBA__&Key-Pair-Id=APKAIGLPRCHE2BH6RZLQ&px-nb=UGtezEZ854jbmFcvWGxLEA==)


here

**Comment by mirh** [comment]
Is there more info about the secure element (I mean, somebody having analyzed the protocol and ruled out other [parameters](https://github.com/ysfchn/SamFetch/blob/main/RESOURCES.md))?
People [here](https://github.com/ivanmeler/SamFirm_Reborn/issues/3) even conversely mentioned that at least the delta packages should be unauthenticated.

I know that's different from the coveted full firmware, but it's still something that may interest some people (hell, even just being able to tell what's the last firmware version like SamLoader-Reloaded and GNSF do could still be a worthwile usecase).
EDIT: [well, damn](https://github.com/zacharee/SamloaderKotlin/issues/427)
