### ISSUE TITLE
Bad request status : 400

### ISSUE THREAD

**Issue by mystic-mady** [zacharee/SamloaderKotlin#166]
I try to download firmware for Samsung Galaxy s20 plus (Bts edition) on Bifrost. But I get Bad request status : 400, I think Odinrom source not working. Can you check it. Thank you

**Comment by mystic-mady** [comment]
> um if that is your IMEI i wouldn't recommend sharing your IMEI number on internet.

Thanks bruh, what the solution for bad request :400?

**Comment by zacharee** [comment]
What model and CSC are you entering?

**Comment by mystic-mady** [comment]
Model - SM-G985F
CSC - INU or XSP

**Comment by zacharee** [comment]
I'm not able to reproduce:

![image](https://github.com/zacharee/SamloaderKotlin/assets/9020352/2d1e2a08-a739-4a4d-9201-7f32bf32225b)

**Comment by mystic-mady** [comment]
I have purple edition BTS version mobile . I want OXB firmware version not
OXM

**Comment by zacharee** [comment]
Use the SIO region.

**Comment by mystic-mady** [comment]
Thanks, I will!
