### ISSUE TITLE
The os does not support: 'Taskbar.setIconImage' message (but tool works well - Windows 10 Pro, 64bit)

### ISSUE THREAD

**Issue by 7wells** [zacharee/SamloaderKotlin#17]
Hello!

I find your tool very useful and it works. Thank you! :-) There is just a minor thing I would like to make you aware of. In Windows 10 (Pro, 64bit), a window opens when executing your tool, showing the below message:
> The os does not support: 'Taskbar.setIconImage'

However, the main window of your tool open separately, and everything seems to work just fine, irrespective of this message. I don't know where this comes from (and it seems to be of minor importance), but I thought you might be interested in this.

If you need more info, please let me know.

**Comment by zacharee** [comment]
Don't worry about that message. It's just for debugging purposes.

**Comment by GravuTrad** [comment]
noted
