### ISSUE TITLE
No changelog with the history tab

### ISSUE THREAD

**Issue by CiprianDinca9** [zacharee/SamloaderKotlin#18]
Samsung provides changelogs for firmwares. By typing model number notify update, you can get the changelogs. I know, it is Samsung mobile, doc.samsungmobile.com. now that we can no longer download from the tab, you can update the website.

**Comment by zacharee** [comment]
Can you provide an example URL?

**Comment by CiprianDinca9** [comment]
[]()https://doc.samsungmobile.com/SM-A202F/DBT/doc.html

**Comment by CiprianDinca9** [comment]
I have commented on GitHub. You can see the link there. That provides lots
of info, especially made for such features. You need to know, I really like
the app and will donate as soon as I can!

**Comment by zacharee** [comment]
Build 0.5.0 will have a changelog for both the retrieved firmware in the Download tab and for each item in the History tab.
