### ISSUE TITLE
New Name

### ISSUE THREAD

**Issue by zacharee** [zacharee/SamloaderKotlin#2]
Samsung Firmware Downloader is a bad name. It's too generic and too long.

If anyone has a suggestion, leave a comment.

___

It shouldn't be something that already exists, like Samloader (ignore the repo name) or SamFirm.

**Comment by mohammad92** [comment]
Also spaces make issue with linux.
samfirmloader, samfirmloaderkot. sflk.

**Comment by david-lev** [comment]
Amazing tool by the way... 
Suggestions:
- Samfirm
- Samloader
- downsamfirm

**Comment by svrselja** [comment]
FirmUp
UpSam 
UpFirmFinder
UpGalaxy
Galaxy Flash data
Samsung Files
SamUpData

**Comment by Frivolous2** [comment]
Bifrost, after the Norse mythology bridge that connects the realm of mortals to the realm of the gods.

**Comment by JET-6** [comment]
Sam's Firm D

**Comment by roynatech2544** [comment]
Samloaderkt

**Comment by zacharee** [comment]
> Bifrost, after the Norse mythology bridge that connects the realm of mortals to the realm of the gods.

This seems like the best option so far. 

I'll wait a bit longer to see if there's another suggestion I like, though.

**Comment by pfhayter** [comment]
Quasar, after flashing lights in our galaxy and beyond.

**Comment by 0n1cOn3** [comment]
Saphirm - Pronounciation from Sa(m) and Saphir + Firm(ware)

Saphir as Contribution to get Samload on the GUI Side. + Cross Platform Support.

**Comment by Frivolous2** [comment]
SamFirm, like XperiFirm https://xperifirm.com/

**Comment by JohnSmithGoogl01** [comment]
Samdicate

**Comment by tcharding** [comment]
-1 for Bifrost (unless its tonuge in cheek). Implies we are the mortals and Samsung the gods - after trying for many days to flash a Samsung device I'd prefer a name that implies Samsung is from the underworld. The fact that we even need to write a tool to connect to them emphasizes my point.

**Comment by tcharding** [comment]
Suggestion: `samfer` (Samsung Firmware Downloader)

**Comment by LuuchoRocha** [comment]
ZSloader

**Comment by CiprianDinca9** [comment]
Suggestion: SamFirmStore.

**Comment by MLXProjects** [comment]
What about SaphirDL? Easily pronounceable and reflects the original name (the PH instead of a F is because of the pronunciation)

**Comment by Githubraum** [comment]
suggestion: Samdowner
short: Samdo

**Comment by CiprianDinca9** [comment]
SaphirDL. I agree with this. It feels like the best option so far.

**Comment by viktorstalzkov** [comment]
SamsFirmLoad

GoodSalad

SolidSandwich / SpringSammich / SamsSub

**Comment by zacharee** [comment]
With version 1.0.0, Samsung Firmware Downloader has been renamed to Bifrost.
