### ISSUE TITLE
Bifrost 1.17.10

### ISSUE THREAD

**Issue by Serg19644** [zacharee/SamloaderKotlin#201]
Bifrost 1.17.10
does the new version on the computer download firmware to the Samsung S24? s24+ s24 ultra, does not download on the phone. writing is prohibited. I installed the previous one, everything is fine. I am attaching a screenshot.

![Screenshot_20240411_094113_Bifrost 1](https://github.com/zacharee/SamloaderKotlin/assets/162879331/0d4a6880-2db9-461a-9705-40914a06fd97)
![Screenshot_20240411_095010_Bifrost 1](https://github.com/zacharee/SamloaderKotlin/assets/162879331/351d4fef-c2a5-4a5d-9e9f-f5422513513d)
![баг](https://github.com/zacharee/SamloaderKotlin/assets/162879331/b6a7a1ee-62a8-415b-bb63-85b4e14847e9)

**Comment by zacharee** [comment]
This should be fixed in 1.17.11.
