### ISSUE TITLE
Access Denied Error

### ISSUE THREAD

**Issue by PitchAbyss** [zacharee/SamloaderKotlin#215]
when searching for a firmware i get this

![image](https://github.com/zacharee/SamloaderKotlin/assets/13099434/8a3f2462-8fc7-4694-9db1-79888934deca)

**Comment by zacharee** [comment]
You need to capitalize the region: INS.

**Comment by PitchAbyss** [comment]
> Allowing lowercase letters just lets you enter lowercase characters into the fields. It doesn't mean Samsung will accept lowercase characters.

Okkk thanks
