### ISSUE TITLE
App force stops when clicking check for updates in the downloader.

### ISSUE THREAD

**Issue by CiprianDinca9** [zacharee/SamloaderKotlin#22]
The only way to enter a firmware in the firmware edit box at the downloader is to check for updates. but the app crashes when you press that button.

**Comment by zacharee** [comment]
![Screenshot_20210715-225740](https://user-images.githubusercontent.com/9020352/126050641-418d2949-57a8-48d7-8647-3ae4892a8e53.jpg)
No problem here. I can't help without a model and region.
