### ISSUE TITLE
Access Denied when click Check Update

### ISSUE THREAD

**Issue by hazukame** [zacharee/SamloaderKotlin#229]
I'm trying to find the firmware for my device but when I fill everything out it shows Access Denied. I think I've done everything I can from running as administrator to installing everything possible on github, but still nothing. I don't know what this is caused by

![image (5)](https://github.com/zacharee/SamloaderKotlin/assets/42877346/9c18a0fa-54d0-4dfd-b9e3-60fea4e4cc57)

**Comment by zacharee** [comment]
Don't include the `/DS`.

**Comment by hazukame** [comment]
> Don't include the `/DS`.

As I said, I tried everything - So also adding /DS, even when it does not add it shows the same Access Denied error

![image](https://github.com/zacharee/SamloaderKotlin/assets/42877346/5c18e8df-ba4b-407c-9499-d513d9af24c7)

**Comment by EFIShell0** [comment]
Just try it as DS. You can also find the code of your device from its box or via Android (such as SM-A105F, SM-X810).
