### ISSUE TITLE
Decryption process fail around 80%

### ISSUE THREAD

**Issue by pbalenzuela** [zacharee/SamloaderKotlin#230]
**Describe the bug**
Unable to decrypt a successfully downloaded rom

**To Reproduce**
1. At First I simply downloaded a specific rom using "downloader" option
```
model: SM-S711B
region: ARO
firmware: S711BXXU1BWK5
file: SM-S711B_2_20240603233141_q68nalyjdg_fac_S711BXXS3CXE8_S711BOLM3CXE8_S711BXXS3CXE8_S711BXXS3CXE8_OPS.zip.enc4
decryption key: 7XXEE1XS/XSX771/
IMEI: my actual IMEI number
```
2. I tried then to decrypt the file using the "decrypter" tool

I both cases it failed after passing 90% of the process

![image](https://github.com/zacharee/SamloaderKotlin/assets/6960265/7b2d340e-7f01-4949-b7f5-5a9b42237dee)

**Expected behavior**
Successfully decrypt the rom

**Screenshots**
![image](https://github.com/zacharee/SamloaderKotlin/assets/6960265/61e553ca-5f28-4185-a79b-a2a10ac06088)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 23H2 build 22631.3737

**Additional context**
I tried other tools and they failed similarly. This might be a problem from Samsung servers

**Comment by zacharee** [comment]
Do you have enough free space on your system for it to decrypt? The error message says you don't.
