### ISSUE TITLE
Cannot download the firmware found by Bifrost on Ubuntu Linux

### ISSUE THREAD

**Issue by laheller** [zacharee/SamloaderKotlin#255]
Hi @zacharee 

Trying Bifrost on Ubuntu Linux, installed from package **bifrost_1.18.13_amd64.deb**.
Bifrost is able to find the latest firmware for my SM-A546B device but on download attempt I have following error message:
![image](https://github.com/user-attachments/assets/8d43b731-9c91-4c61-a254-f892a1b761ab)

![image](https://github.com/user-attachments/assets/e93aa2ab-9055-4c9b-a9b0-a69811d567d6)

Any suggestions?

BR,

Ladislav

**Comment by zacharee** [comment]
I think this has something to do with your network configuration, possibly from some MITM certificate VMware installs. I can't reproduce this in Parallels.
