### ISSUE TITLE
1.19.2 bifrost

### ISSUE THREAD

**Issue by Serg19644** [zacharee/SamloaderKotlin#269]
На версии для windows скачивает файл CRC и удаляет. Прошивку не удаётся скачать. На версии 1.19.1 всё нормально работает.

On the windows version, downloads the CRC file and deletes it. The firmware cannot be downloaded. Everything works fine on version 1.19.1.

**Comment by Serg19644** [comment]
The program downloads the firmware, but after downloading it checks and deletes it. At the end of the download, the zip file weighs 0 bytes

**Comment by WesSec** [comment]
I think it has to do with the save window trying to save it as .zip instantly instead of enc4

**Comment by zacharee** [comment]
This should be fixed in 1.19.3, which is building now.

**Comment by Serg19644** [comment]
Fixed in version 1.19.3. Everything is working now, thanks.
