### ISSUE TITLE
Bug in filware download

### ISSUE THREAD

**Issue by Tech560** [zacharee/SamloaderKotlin#272]
After downloading official filmware from SM-T590 via Bitfrost and installing it, I see that the recovery name/version is listed twice, see photo. I have already re-flashed and downloaded several times, but nothing has changed.
Feedback![20240831_210425.jpg](https://github.com/user-attachments/assets/79ec472c-0d4d-43f5-ab6b-1c95d2473c00)

**Comment by zacharee** [comment]
Bifrost serves firmware directly from Samsung, exactly as Samsung provides. If the firmware CRC verified successfully and the device flashed and booted the firmware, then this isn't related to Bifrost.

**Comment by Tech560** [comment]
Thanks for to quik anwser
