### ISSUE TITLE
Get error bad status 400 return when I'm trying to download the latest firmware in some device model

### ISSUE THREAD

**Issue by misterfocusth** [zacharee/SamloaderKotlin#28]
**Describe**
I'm trying to download the latest firmware version for my device that is Galaxy S21 Ultra 5G (SM-G998B) but It's always return me error bad status 400 when I'm trying to press download button, and It not only on my PC but on my phone when I'm trying to download using your application I get error bad status 400 same as I get on my PC. 

![image](https://user-images.githubusercontent.com/53871704/131223193-d30eaef0-98fd-40bb-bbd3-06f5cc9c9020.png)

and in command line it show an error like this
`java.lang.Exception: Bad return status: 400                                                                                                                                                                            at tk.zwander.common.tools.Request.getBinaryFile(Request.kt:172)                                                                                                                                               at tk.zwander.common.tools.Request$getBinaryFile$1.invokeSuspend(Request.kt)                                                                                                                                   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                                                                                                                      at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)                                                                                                                          at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)                                                                                                                                    at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)                                                                                                                              at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)                                                                                                                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)                                                                                                                      at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)                                                                                                                          at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)                                                                                                                                    at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)                                                                                                                              at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)                                                                                                                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)                                                                                                                      at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)                                                                                                                          at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)                                                                                                                                    at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)                                                                                                                              at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)                                                                                                                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)                                                                                                                      at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)                                                                                                                          at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)                                                                                                                                    at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)                                                                                                                              at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)                                                                                                                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)                                                                                                                      at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)                                                                                                                          at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)                                                                                                                                    at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)                                                                                                                              at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)                                                                                                                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)                                                                                                                      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)                                                                                                                                                at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)                                                                                                                                        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)                                                                                                                                          at java.desktop/java.awt.EventQueue$4.run(Unknown Source)                                                                                                                                                      at java.desktop/java.awt.EventQueue$4.run(Unknown Source)                                                                                                                                                      at java.base/java.security.AccessController.doPrivileged(Unknown Source)                                                                                                                                       at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)                                                                                                     at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)                                                                                                                                              at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)                                                                                                                            at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)                                                                                                                               at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)                                                                                                                            at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)                                                                                                                                        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)                                                                                                                                        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)            `

**Here is about device model and firmware that I'm trying to download**
Device : Samsung Galaxy S21 Ultra 5G (SM-G998B)
Region : Thailand (THL)
Firmware (PDA/CSC/CP/AP) : G998BXXU3AUHB/G998BOXM3AUHB/G998BXXU3AUHB/G998BXXU3AUHB

(But I think It's was problem with only this latest firmware version that I'm trying to download, because I'm try to download firmware on another device model It can download perfectly.)

**To reproduce this issue**
trying to download firmware for Galaxy S21 Ultra 5G (**SM-G998B**) region **THL** and Firmware (PDA/CSC/CP/AP) : **G998BXXU3AUHB/G998BOXM3AUHB/G998BXXU3AUHB/G998BXXU3AUHB** for now this version is the latest version of my device and that is firmware that I want to download.

**Comment by zacharee** [comment]
This is on Samsung's end. Use a different CSC.
