### ISSUE TITLE
عدم القدره علي تحديث جهازي

### ISSUE THREAD

**Issue by HaithamALMTARY** [zacharee/SamloaderKotlin#286]
![Screenshot_٢٠٢٤٠٣٢٩-٠٠٣٠٢٨_System updates UI](https://github.com/user-attachments/assets/70d89c4e-5bc9-4ef3-a8cd-83093817ee24)

**Comment by zacharee** [comment]
Bifrost is an app to manually download firmware you flash using a computer with Odin. It doesn't do anything with OTAs.
