### ISSUE TITLE
SM-G985F downloads BTS edition

### ISSUE THREAD

**Issue by TotallyNotInUse** [zacharee/SamloaderKotlin#291]
**Describe the bug**
When downloading firmware for the SM-G985F (Galaxy S20+ 4G) with GTO region, it downloads the firmware for the BTS edition despite the phone not being the BTS edition.

**To Reproduce**
1. Choose SM-G985F as the model
2. Choose GTO as the region
3. Download firmware
4. Flash using Odin
5. Device has BTS special edition

**Expected behavior**
Other times it has downloaded the normal firmware.

**Screenshots**
![image](https://github.com/user-attachments/assets/c963502b-d841-4cb4-9737-821752107aa7)

**Desktop (please complete the following information):**
 - OS: Windows 11 (10.0.22631.4317)
 - Bifrost Version: 1.19.4
 - Firmware reported by Bifrost: G985FXXSLHXG1/G985FOXBLHXH2/G985FXXSLHXG1/G985FXXSLHXG1

**Smartphone (please complete the following information):**
 - Device: Galaxy S20+ 4G (SM-G985F)
 - OS: Android 13
 - Build number: TP1A.220624.014.G985FXXSLHXG1

**Comment by zacharee** [comment]
This isn't something Bifrost can fix. Samsung chooses what firmware is served for a given model and CSC.
