### ISSUE TITLE
Throwing exceptions while running on Windows 7 systems

### ISSUE THREAD

**Issue by thisbing** [zacharee/SamloaderKotlin#292]
**Describe the bug**
I executed Bifrost\bin\Bifrost.exe and the operating system popped up an error message: java.lang.UnstatisLinkError:error looking up function 'IsWow64Process2'.
The full path to Bifrost is D:\Bifrost\bin\Bifrost.exe with no spaces.

**To Reproduce**
1. Go to D:\Bifrost\bin
2. Click on Bifrost.exe
3. throw an exception: java.lang.UnstatisLinkError:error looking up function 'IsWow64Process2'.

**Expected behavior**

**Screenshots**
Opens normally and downloads firmware quickly.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 7 Service Pack 1
 Bifrost Version: 1.19.4

Thank you very much for providing this tool. I hope this problem can be solved as soon as possible. I wish you a happy life and all the best.

![Snipaste_1](https://github.com/user-attachments/assets/aecc170c-06fc-423c-8997-43cdbea81606)
![Snipaste_2](https://github.com/user-attachments/assets/f28a3de2-6b91-4f7f-9bda-ebd3413c8cef)

**Comment by zacharee** [comment]
This should be fixed in 1.19.5.

**Comment by thisbing** [comment]
Fixed in version 1.19.3. Everything is working now, thanks.
