### ISSUE TITLE
Samsung Galaxy 7 Download firmware with Bifrost

### ISSUE THREAD

**Issue by Smart0811** [zacharee/SamloaderKotlin#306]
I have tried to download the latest firmware (German or EU) for Galaxy 7 Watch with Bifrost.
With the model SM-L310 and the the correct country selection the latest firmware can be found. After pushing the download bottom I get the error "Schlechter Rückgabestatus: 400". See the attached picture.

Can somebody help?

(Unfortunately the picture is in German)

<img width="804" alt="Bildschirmfoto 2024-12-28 um 11 42 02" src="https://github.com/user-attachments/assets/47ccef86-e81d-4357-913c-6a9ef47bf7a6" />

**Comment by zacharee** [comment]
Please see the README: https://github.com/zacharee/SamloaderKotlin?tab=readme-ov-file#bifrost-isnt-downloading-watch-firmware
