### ISSUE TITLE
After successful de-encryption, the encrypted file is not deleted in Windows 11

### ISSUE THREAD

**Issue by jtash** [zacharee/SamloaderKotlin#36]
After successful de-encryption of the encrypted zip it is not deleted when the zip file has been successfully created. (v0.5.2 on Windows 11).

**Comment by zacharee** [comment]
That's intended behavior to provide consistency among platforms. Because of a bug in Java, you'll need to close the app to delete the file.

**Comment by jtash** [comment]
Ok. Good to know

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by GravuTrad** [comment]
Damage but noted
