### ISSUE TITLE
No size details at the firmware history. Can you add it?

### ISSUE THREAD

**Issue by CiprianDinca9** [zacharee/SamloaderKotlin#37]
Actually, this one would be a fairly big thing and quite important because we would actually know what really happened with the update. You know? When downloading one from settings, you get a size thing. I would be really glad if you could do such a thing. Also, there are some phone's which don't have changelogs, best example I met is the Galaxy A8, SM-A530F. For that, try putting the size before expanding changelogs. Thanks and best regards!

**Comment by zacharee** [comment]
The file size is retrieved from Samsung's servers. OdinRom doesn't provide a way to view the file size for historical firmware versions.
