### ISSUE TITLE
Application runtime error

### ISSUE THREAD

**Issue by gidano** [zacharee/SamloaderKotlin#4]
Hi,
Unfortunately, I can't run the app. I attach a screenshot and log file, I want to ask for help. I can't resolve the error...

![vlcsnap-2021-03-14-09h47m29s163](https://user-images.githubusercontent.com/4068977/111063191-8b86ad80-84ad-11eb-9ab7-ad63ff216662.png)
[hs_err_pid2988.log](https://github.com/zacharee/SamloaderKotlin/files/6136344/hs_err_pid2988.log)

**Comment by zacharee** [comment]
I've reported this issue to the JetBrains team to see if they know what's happening. They might need additional information, Would you mind subscribing to the issue and responding if needed?

https://github.com/JetBrains/skiko/issues/72

**Comment by qbrian** [comment]
@gidano 
I get the same and even worse because on attempt 2 nothing came out and the solution was to run it as administrator
![Sin título](https://user-images.githubusercontent.com/36779899/111074824-53866700-84bb-11eb-8a9d-1d3f871aa76d.png)

**Comment by gidano** [comment]
Thanks, I tried but the phenomenon is the same!

**Comment by gidano** [comment]
> I've reported this issue to the JetBrains team to see if they know what's happening. They might need additional information, Would you mind subscribing to the issue and responding if needed?
> 
> [JetBrains/skiko#72](https://github.com/JetBrains/skiko/issues/72)

Of course, I'll help if I can.

**Comment by qbrian** [comment]
@gidano,  I understand, it's fine, perfect

-regards [ @gidano , @zacharee ]

**Comment by gidano** [comment]
I was hoping this morning that v0.3.2 would work for me too. But the same phenomenon as in previous versions.

**Comment by qbrian** [comment]
Oh :c 
Hello, I understand, did you try to update the graphics and java drivers, and those determined by windows and windows itself?

**Comment by qbrian** [comment]
look here https://github.com/zacharee/SamloaderKotlin/compare/0.3.2...master#commits_bucket

**Comment by gidano** [comment]
I have never had a problem with my Intel video card, the latest driver is installed for every device.
Now turning off Intel has solved the problem, starting the application using AMD Radeon.
Regardless, I think it should work smoothly with the internal Intel card as well, its use has never been a problem. I just work on the machine, I don't play... :)
Thanks to everyone who tried to help!
![screenshot_20210316_165611](https://user-images.githubusercontent.com/4068977/111341124-84ac9600-8679-11eb-87b8-c2d41922bc5c.png)
