### ISSUE TITLE
Download firmware 

### ISSUE THREAD

**Issue by Mudds90** [zacharee/SamloaderKotlin#41]
Need help to download the SM-A9080B firmware and not with a zip file please

**Comment by zacharee** [comment]
Sorry, but I'm not sure what you're asking. There is no SM-A9080B, only an SM-A9080 and an SM-N908B. All firmware comes in ZIP files.

**Comment by Mudds90** [comment]
A9080 firmware please

**Comment by gr33n1975** [comment]
Hello, i tried to download firmware for S7 Edge and it downloaded a encrypted file with extention enc4, i tried to decrypt it with your tool in the tab decryption and nothing happened, what am i doing wrong? Kind regards
