### ISSUE TITLE
Glaxy Watch Series firmware couldnt download

### ISSUE THREAD

**Issue by Desomnd** [zacharee/SamloaderKotlin#44]
My Galaxy Watch3 (TGY/CHC)want to download the firmware in bifrost.I enter the model and CSC,bifrost got the PDA.But when I download,it show me the 400 bad return status,just like this.
![Screenshot_20211222-005637](https://user-images.githubusercontent.com/49361700/146969756-d9edc52a-bef6-4305-b3a3-604767b1a34b.jpg)
Although I don't know what happened in bifrost,but I can try my best to help solve this problem.

**Comment by zacharee** [comment]
You can't download watch firmware directly.

**Comment by Desomnd** [comment]
So how could I download it？

**Comment by zacharee** [comment]
I don't know, sorry.
