### ISSUE TITLE
downloading latest firmware has inconsistent speed

### ISSUE THREAD

**Issue by random2907** [zacharee/SamloaderKotlin#45]
![Screenshot 2021-12-27 205000](https://user-images.githubusercontent.com/81547183/147485080-9d43df1c-a1e9-4ced-a888-fe60ee77c2e9.png)

speed fluctuate between kb and mb 
it also stuck when downloading

**Comment by zacharee** [comment]
Samsung sometimes throttles downloads. I can't really control that.
