### ISSUE TITLE
Trying to Download Firmware Results in a weird Error(?)

### ISSUE THREAD

**Issue by adikpb** [zacharee/SamloaderKotlin#46]
![Screen Shot 2021-12-28 at 12 07 32 AM](https://user-images.githubusercontent.com/67222969/147504018-b6f93874-b0fa-458f-aa07-f6485dc8a7fe.png)
![Screen Shot 2021-12-28 at 12 07 42 AM](https://user-images.githubusercontent.com/67222969/147504026-f57d238b-4844-45be-9ce9-1d75fbf3ca84.png)
![Screen Shot 2021-12-28 at 12 07 47 AM](https://user-images.githubusercontent.com/67222969/147504039-82ee9962-04e8-4043-869d-a5d3dae3d3a4.png)
![Screen Shot 2021-12-28 at 12 07 57 AM](https://user-images.githubusercontent.com/67222969/147504049-e0ae836e-9ad2-4e37-a5fd-7589911bd948.png)
![Screen Shot 2021-12-28 at 12 08 02 AM](https://user-images.githubusercontent.com/67222969/147504055-867838e7-1117-48fb-a78c-201af7901cea.png)
![Screen Shot 2021-12-28 at 12 08 09 AM](https://user-images.githubusercontent.com/67222969/147504065-9b04872f-b35b-47d5-8d8a-119bce3ea208.png)
![Screen Shot 2021-12-28 at 12 08 13 AM](https://user-images.githubusercontent.com/67222969/147504076-7064d7e3-1133-47de-95d8-52e158d6b1ff.png)
![Screen Shot 2021-12-28 at 12 08 18 AM](https://user-images.githubusercontent.com/67222969/147504085-6a455c0d-a729-4eee-b5b0-8f12f17b5b61.png)
![Screen Shot 2021-12-28 at 12 08 21 AM](https://user-images.githubusercontent.com/67222969/147504092-73ad96bc-1946-4f19-9dc6-844269550455.png)
![Screen Shot 2021-12-28 at 12 08 25 AM](https://user-images.githubusercontent.com/67222969/147504099-8845db0e-1bbe-445d-b021-88a2e572a14c.png)
![Screen Shot 2021-12-28 at 12 08 31 AM](https://user-images.githubusercontent.com/67222969/147504107-666b77a0-fe17-4ba1-a0f1-c02c95a5e236.png)
![Screen Shot 2021-12-28 at 12 08 35 AM](https://user-images.githubusercontent.com/67222969/147504115-66c32004-7ec3-4b22-9b33-42f499c87fac.png)
![Screen Shot 2021-12-28 at 12 08 39 AM](https://user-images.githubusercontent.com/67222969/147504119-c71fc2b6-b6d5-42d8-8b8e-c000dcfa5140.png)

**Comment by zacharee** [comment]
Samsung isn't hosting the firmware for that device and CSC. Try XFA.

**Comment by adikpb** [comment]
Ah I see. Btw did you mean XDA? Thank you.

**Comment by zacharee** [comment]
No, XFA is the South Africa CSC, which does have firmware available.

Zachary Wander

**Comment by adikpb** [comment]
Ah thank you.
