### ISSUE TITLE
Blank page when I start the SamloaderKotlin

### ISSUE THREAD

**Issue by Fab0284981** [zacharee/SamloaderKotlin#47]
Hi guys! 
On my notebook I am trying to start the software, but unfortunately when I start I only get a blank page (nothing more). No logs etc.
I also tried starting it with admin privileges 
My Notebook and Windows version:
Edition: Windows 10 Home 21H2 64Bit 
Build System: 19044.1415
Processor: Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz   1.70 GHz
but in windows 11 it's working and is perfect.

Thanks!!!!

p.s this is a screenshot: 
https://ibb.co/gmbkW9b

**Comment by zacharee** [comment]
Can you see if 1.0.4 works any better?

**Comment by Fab0284981** [comment]
Hi! i have the 1.0.5 and nothing...
Blank Page...
https://ibb.co/3rTc5S4

**Comment by zacharee** [comment]
Does running the program as an administrator help?
