### ISSUE TITLE
Windows 7 problem. 

### ISSUE THREAD

**Issue by DQuealey** [zacharee/SamloaderKotlin#5]
When installing V 3.0.1, Windows 7 pro. Says this program isn't compatible with this version of windows.. It apparently can't tell if it's a 32 or 64 bit program.

**Comment by zacharee** [comment]
Are you on a 32-bit or 64-bit version of Windows?

**Comment by zacharee** [comment]
I'm going to guess it's 32-bit, since I get a similar error with a 32-bit virtual machine. Unfortunately, JetBrains Compose doesn't currently support 32-bit builds.

**Comment by DQuealey** [comment]
I do believe it is a 32 bit system Zach.. Bummer! Maybe in future updates you'll make it 32 compatable?

I'm sure a lot of us would enjoy this work!

Darrwll.



Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone



-------- Original message --------
From: Zachary Wander ***@***.***>
Date: 3/14/21 12:04 PM (GMT-08:00)
To: zacharee/SamloaderKotlin ***@***.***>
Cc: DQuealey ***@***.***>, Author ***@***.***>
Subject: Re: [zacharee/SamloaderKotlin] Windows 7 problem. (#5)


I'm going to guess it's 32-bit, since I get a similar error with a 32-bit virtual machine. Unfortunately, JetBrains Compose doesn't currently support 32-bit builds.

**Comment by DQuealey** [comment]
Yes, Sir....



Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone



-------- Original message --------
From: Zachary Wander ***@***.***>
Date: 3/14/21 10:59 AM (GMT-08:00)
To: zacharee/SamloaderKotlin ***@***.***>
Cc: DQuealey ***@***.***>, Author ***@***.***>
Subject: Re: [zacharee/SamloaderKotlin] Windows 7 problem. (#5)


Are you on a 32-bit or 64-bit version of Windows?

**Comment by zacharee** [comment]
There isn't anything I can do directly.

**Comment by DQuealey** [comment]
I understand



Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone



-------- Original message --------
From: Zachary Wander ***@***.***>
Date: 3/15/21 8:45 AM (GMT-08:00)
To: zacharee/SamloaderKotlin ***@***.***>
Cc: DQuealey ***@***.***>, Author ***@***.***>
Subject: Re: [zacharee/SamloaderKotlin] Unable to open on 32-bit operating system (#5)


There isn't anything I can do directly.
