### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by lolinajdi** [zacharee/SamloaderKotlin#50]
hello there is some issues 

first : the downloading speed is slow Although my wifi is fast.

Secondly : when I run the program its show like this 
![InkedScreenshot 2022-01-09 141043_LI](https://user-images.githubusercontent.com/65453926/148679775-c7ff9ef2-76c0-4b2e-8564-cda43c6f2855.jpg)

my directX is latest version

my laptop os windows 10 pry 64 bit

**Comment by TheAirBlow** [comment]
First: Different servers have different speeds, your ISP can have issues with a specific server, etc.
Second: Video driver lol

**Comment by zacharee** [comment]
Speeds depend on Samsung's servers.
