### ISSUE TITLE
Can't download SM-G970F firmware (Bad return status: 400)

### ISSUE THREAD

**Issue by pmarcus93** [zacharee/SamloaderKotlin#53]
When I try to download the SM-G970F firmware (ZTO region), I'm getting the following error message:

![image](https://user-images.githubusercontent.com/6492177/153757739-1c6da617-1432-493e-be13-6dcb9b1f3ebc.png)

OS: Windows 11 (x64)
I'm running the app as an administrator.

**Comment by fildunsky** [comment]
I got same error for SM-G991B SIN region (firmware 4BVA8)

**Comment by zacharee** [comment]
This is an issue on the server side. You'll have to try a different region.

**Comment by pmarcus93** [comment]
@zacharee thanks!
