### ISSUE TITLE
More Info: connection reset

### ISSUE THREAD

**Issue by LeoAdavirat** [zacharee/SamloaderKotlin#58]
I tried to download a firmware and got into this issue, looking forward to a fix. Thank you in advance
![image](https://user-images.githubusercontent.com/52106425/160242919-1a87dda0-571f-492d-8f06-028a07e9ab50.png)

**Comment by zacharee** [comment]
This is an issue with your internet connection.

**Comment by Leo17032009** [comment]
> .
No, I have the same problem.![Screenshot_20220415-182124_Bifrost.jpg](https://user-images.githubusercontent.com/89399852/163588926-5c6cdefa-ed8e-4b32-af53-cd6d0b5c4bdd.jpg)

**Comment by zacharee** [comment]
> > .
> > No, I have the same problem.![Screenshot_20220415-182124_Bifrost.jpg](https://user-images.githubusercontent.com/89399852/163588926-5c6cdefa-ed8e-4b32-af53-cd6d0b5c4bdd.jpg)

Your error is 403 and it's because you put in XVV instead of XXV
