### ISSUE TITLE
Getting strange error and download doesnt start

### ISSUE THREAD

**Issue by ifelixculpa** [zacharee/SamloaderKotlin#65]
![Screenshot_1](https://user-images.githubusercontent.com/13099434/170837781-aa05f766-e48e-412c-9223-d95a14d9e458.png)

**Comment by zacharee** [comment]
What model and region are you entering?

**Comment by Ickerday** [comment]
I get the same when entering SM-G781U1 with XAA region.

**Comment by ifelixculpa** [comment]
> @Ickerday I can't reproduce the issue with that combination on 1.0.10.

because on this version i am getting new error

![image](https://user-images.githubusercontent.com/13099434/180570077-22856157-bce1-44ef-b34b-840c895bcf5f.png)

**Comment by zacharee** [comment]
Try 1.0.11 once it builds.

**Comment by ifelixculpa** [comment]
> Try 1.0.11 once it builds.

working fine now , thanks dev
