### ISSUE TITLE
There's no way to know when an update has been launched, no notifications system

### ISSUE THREAD

**Issue by CiprianDinca9** [zacharee/SamloaderKotlin#66]
Very useful. For example, you are following updates from another region.
Here is how it should work. If you enter a model number and a region, a monitor button should appear in the more options menu. But only after you have a name and a region typed should the button appear. After clicking the button, the app should announce you when new updates come for that model number, in that region.

**Comment by zacharee** [comment]
This isn't really part of the app's scope, and would be difficult to implement cross-platform, especially on Linux.
