### ISSUE TITLE
"Working..." notification not dismissing when closing the app.

### ISSUE THREAD

**Issue by Leo17032009** [zacharee/SamloaderKotlin#67]
![Screenshot_20220604-140807_One UI Home.jpg](https://user-images.githubusercontent.com/89399852/171996464-4aded002-ca02-4cb6-9524-51214bcbec76.jpg)

**Comment by zacharee** [comment]
Have you removed the app from Recents?

**Comment by Leo17032009** [comment]
> Have you removed the app from Recents?

How do I do this?

**Comment by zacharee** [comment]
https://user-images.githubusercontent.com/9020352/174441994-51e22d27-b0b5-492b-9aad-aaa5ae105e08.mp4

**Comment by Leo17032009** [comment]
https://drive.google.com/file/d/1MKOGYShn5Ys2F6mHqhAOUIJp1hfyQbAQ/view?usp=drivesdk

**Comment by languagemaniac** [comment]
I am also having this issue. It successfully downloaded and decrypted a firmware but the notification got stucked saying "working..."and "decrypting 99.98%"

I had to force close the app from the settings. As closing the program did nothing.

Opening the app again causes the same notification to appear (only it doesn't display "decrypting" info) , but closing the program does make the notification disappear.

Other than that it works great.

I hope this information can help you fix the issue.

**Comment by jmichael2497** [comment]
still happening on stock SM-T500 with final A12 running v1.20.2 android app seems to show successful download and decrypt, but notification was stuck saying something like decrypt in progress 99.2% so closed app to clear that.
