### ISSUE TITLE
Input and Glitches

### ISSUE THREAD

**Issue by HorrorBest** [zacharee/SamloaderKotlin#7]
When I open The App ( Latest Release by the time of 16/03/2021 ) When I try To click something It won't click and sometimes The Menu moves and kinda flashes... I cant explain it in words but It glitches

**Comment by HorrorBest** [comment]
It shows both of these menus one after the other but fast
![image](https://user-images.githubusercontent.com/75090757/111313891-2d023080-8661-11eb-9d59-cdd61b94832d.png)
![image](https://user-images.githubusercontent.com/75090757/111314058-54f19400-8661-11eb-8286-7064b1d6b4a9.png)

**Comment by zacharee** [comment]
Can you try resizing the window a bit?
