### ISSUE TITLE
Resource files\heart.svg not found

### ISSUE THREAD

**Issue by abulalarabi** [zacharee/SamloaderKotlin#73]
In the last update, I am getting an error _Resource files\heart.svg not found_. The android version is working fine. The windows version is not. 
![image](https://user-images.githubusercontent.com/68565388/178379152-5401b7a8-9496-4530-a284-2bba3b04c8bc.png)

**Comment by zacharee** [comment]
Should be fixed in 1.0.10: https://github.com/zacharee/SamloaderKotlin/releases/tag/1.0.10.
