### ISSUE TITLE
Access is Denied

### ISSUE THREAD

**Issue by FoxyTheThird** [zacharee/SamloaderKotlin#74]
I have a Samsung Galaxy S7 Active.

Model Number: SM-G891A

Region Code: ATT

Does anyone know what the problem is?

![Screenshot 2022-07-16 210501](https://user-images.githubusercontent.com/94941964/179379761-ec1cee00-44b5-4fa2-88bf-4df54be3dca0.png)

**Comment by zacharee** [comment]
Unfortunately, you can't download AT&T or Verizon firmware directly from Samsung's servers.
