### ISSUE TITLE
What is Backdoor.Bifrose?

### ISSUE THREAD

**Issue by younyokel** [zacharee/SamloaderKotlin#77]
Hello, I just installed Bifrost and Malwarebytes gave me a warning that Bifrost.exe contains a backdoor trojan.

**Comment by parkerlreed** [comment]
Seems like a false detection because of the name.

Bifrost / Bifrose

**Comment by zacharee** [comment]
I've added some information to the README. As far as I can tell, it's a false positive based purely on the matching name.
