### ISSUE TITLE
Hungarian translate

### ISSUE THREAD

**Issue by gidano** [zacharee/SamloaderKotlin#79]
Hi,
I completed the Hungarian translation on the Crowdin site, quite some time ago.
Can I count on the release in Hungarian recently?
Regards,
gidano

**Comment by gidano** [comment]
I did the translation almost 4 months ago, but I don't see the Hungarian language in the new 1.12 release.
Is there a practical reason for this?

**Comment by gidano** [comment]
The 1.13.0 version released yesterday does not include the Hungarian translation on Crowdin, which was introduced a few months ago. May I know why! :/

**Comment by gidano** [comment]
The 1.13.0 version released yesterday does not include the Hungarian translation on Crowdin, which was introduced a few months ago. May I know why! :/

**Comment by zacharee** [comment]
I'm still waiting for the localization libraries to mature enough for translations to work properly. They have some issues that make them difficult to use.
