### ISSUE TITLE
dont open

### ISSUE THREAD

**Issue by sdgrs546547Q** [zacharee/SamloaderKotlin#8]
The program dont open on WIndows 10 x64 bits.

**Comment by zacharee** [comment]
Cool.

**Comment by sdgrs546547Q** [comment]
what is wrong with you?

**Comment by amaterasushen** [comment]
Cool.

**Comment by dazemc** [comment]
Solved by running in Windows 8 compatibility mode

[hs_err_pid9828.log](https://github.com/zacharee/SamloaderKotlin/files/6253796/hs_err_pid9828.log)
