### ISSUE TITLE
Small Issue T-545 ROM Download Suffix _B2BF Bifrost

### ISSUE THREAD

**Issue by Dracxabi** [zacharee/SamloaderKotlin#81]
Hi all, 

I have a small issue with the Samsung T-545 (X-Cover 5, PHE) i'm using v.1.0.11 Bifrost App in Android. When I try a last ROM (Android 11) the App say me " Your Request  T545XXS3CVE1_B2BF... but Samsung is attempting to serve T545XXS3CVE... instead. Aborting!.

I think I have the problem because they have added the suffix _B2BF, example T545XXS3CVE1_B2BF...

Thank you. 

![photo_2022-10-13_09-55-23](https://user-images.githubusercontent.com/11947547/195536921-e0e2ac7c-bd4e-473f-9f71-59fea3cff1b4.jpg)

**Comment by zacharee** [comment]
This should be fixed in https://github.com/zacharee/SamloaderKotlin/releases/tag/1.12.0
