### ISSUE TITLE
400: Bad Request when trying to download Fold 4 firmware

### ISSUE THREAD

**Issue by miuirussia** [zacharee/SamloaderKotlin#83]
Model: SM-F936B
Region: XXV

![image](https://user-images.githubusercontent.com/1270028/202419533-bd0e400a-1981-4b61-a264-27eac444e47e.png)

**Comment by zacharee** [comment]
It works fine for me. 400 errors aren't something I can fix. Samsung's CDN may not be serving the file properly in your region, or you might need to just try again. You can also try using a different CSC.
