### ISSUE TITLE
CRC Verify Failed

### ISSUE THREAD

**Issue by thewolfprod** [zacharee/SamloaderKotlin#84]
Happens everytime I'm trying to download firmware on 400 - 500 mb downloaded.
![crcfail](https://user-images.githubusercontent.com/55655314/209477742-55fa09cd-41a4-4cad-9685-1be7cfab9564.png)

**Comment by zacharee** [comment]
Try a different region code. Samsung may not be properly serving the firmware for that region.

**Comment by namrabtw** [comment]
<img width="1121" alt="Screenshot 2023-09-23 at 22 30 11" src="https://github.com/zacharee/SamloaderKotlin/assets/71268918/dc0b18f5-26b0-4084-8bf3-f79dbd7b5042">

I always get the same thing and changing region isn't helping.

**Comment by rscm** [comment]
Same here

OS: Linux Fedora Silverblue 38

Changed between all csc of my country, same result
