### ISSUE TITLE
Why can I not download the firmware for the Dual SIM version of the Galaxy S22 Ultra (SM-S908E/DS)?

### ISSUE THREAD

**Issue by ghost** [zacharee/SamloaderKotlin#88]
### Expected Behavior:

1. When I enter the S22 Ultra's model number and corresponding CSC (in my case, XSA), the firmware downloads.

### Actual Behavior

1.  This shows up on screen:
<img width="590" alt="Capture" src="https://user-images.githubusercontent.com/121598748/209912876-b330ddc9-c87f-4563-8fc5-c074718839a3.PNG">

### Additional Notes

1. For reasons unknown, removing the "/DS" trailing end at the end of the model name allows the firmware to download as normal.
<img width="586" alt="Capture2" src="https://user-images.githubusercontent.com/121598748/210050273-6e603c05-9484-4318-9529-6d224985fa7c.PNG">

**Comment by zacharee** [comment]
In terms of firmware, there's no difference between the dual SIM and single SIM variants. The firmware for the S908E is the firmware for the S908E/DS.
