### ISSUE TITLE
Crashes when trying to enter something in the model number field. 

### ISSUE THREAD

**Issue by coderx546** [zacharee/SamloaderKotlin#89]
Using an Android phone. Samsung galaxy A03 running one UI 5 core rooted.

**Comment by zeca22** [comment]
same here
samsung s22+   A13
i cant do anything from app, always  crashing
[Log_2023-02-06_05-42-08.txt](https://github.com/zacharee/SamloaderKotlin/files/10660064/Log_2023-02-06_05-42-08.txt)

**Comment by hyperio546** [comment]
> same here
> samsung s22+   A13
> i cant do anything from app, always  crashing
> [Log_2023-02-06_05-42-08.txt](https://github.com/zacharee/SamloaderKotlin/files/10660064/Log_2023-02-06_05-42-08.txt)

This version seems pretty much broken. Downgrading works.

**Comment by zacharee** [comment]
Should be fixed with https://github.com/zacharee/SamloaderKotlin/releases/tag/1.13.1

**Comment by coderx546** [comment]
> Should be fixed with https://github.com/zacharee/SamloaderKotlin/releases/tag/1.13.1

Sure thanks.
