### ISSUE TITLE
Windows and Android versions are not working properly.

### ISSUE THREAD

**Issue by Star-Seven** [zacharee/SamloaderKotlin#90]
[CUsersStarDesktopBifrostBifrost.exe.txt](https://github.com/zacharee/SamloaderKotlin/files/10740384/CUsersStarDesktopBifrostBifrost.exe.txt)
[data_app_crash@1676445870170.txt](https://github.com/zacharee/SamloaderKotlin/files/10740385/data_app_crash%401676445870170.txt)

**Comment by zacharee** [comment]
Are you connected to the internet?

**Comment by Star-Seven** [comment]
> 
Yes, there is no problem with my network. The old version of Bifrost (v1.0.11) can also be used normally. Versions after v1.0.11 will not work properly!
![v1 0 11](https://user-images.githubusercontent.com/72426083/219227854-ca101c3d-50ae-4fcb-8509-ef71e9de8c27.png)
![v1 12](https://user-images.githubusercontent.com/72426083/219227860-cfbbe082-4c82-4a62-a779-801a88788f25.png)

**Comment by zacharee** [comment]
I can't reproduce this issue. The part where it's crashing is attempting to connect to `raw.githubusercontent.com`. Do you have that domain blocked?

**Comment by Star-Seven** [comment]
No blocking was done. This should be my network provider's problem. But in the same case, I can use the old version v1.0.11 normally.

**Comment by zacharee** [comment]
1.14.0 should no longer crash.

**Comment by Star-Seven** [comment]
Ok, thank you very much. I will test it!

**Comment by Star-Seven** [comment]
> 1.14.0 should no longer crash.

V1.14.0 has been tested. Windows and Android versions can work normally. Thank you!
