### ISSUE TITLE
Weird save option window

### ISSUE THREAD

**Issue by michelle1574** [zacharee/SamloaderKotlin#92]
Please explain me, why?
![obraz](https://user-images.githubusercontent.com/70703680/224471403-21daf2b2-0296-4483-b4e9-b3e9cdb52a64.png)
you can't use the default Explorer one?

**Comment by zacharee** [comment]
You can turn on "Use Native File Picker" by pressing the settings gear in the bottom right, but the file picker available for Java applications on Windows looks like this: 

![Image](https://user-images.githubusercontent.com/9020352/224482752-d40e220f-964c-4b1d-8de0-83421c5089bf.png)
