### ISSUE TITLE
Bad Return status: 400 | Galaxy Note 4 SM-N910C XEO

### ISSUE THREAD

**Issue by Unknown78** [zacharee/SamloaderKotlin#94]
I have run as Admin
I have the latest Bifrost 1.14.1
I have the latest Eclipse Temurin JDK with Hotspot 19.0.2+7

`N910CXXU2DVH2/N910COXA2DVH2/N910CXXU2DVH2/N910CXXU2DVH2`

![screenshot 1679497145](https://user-images.githubusercontent.com/25132599/226947571-08a12258-000d-483f-8485-e86b8f6fa3ff.png)

P.S. This is on a machine with Intel HD Graphics 5300 as the only GPU.

**Comment by Unknown78** [comment]
This problem is similar with samfirm.js that it can't download the firmware properly.
I have opened the issue there but received no reply yet:
[TypeError: Cannot read properties of undefined (reading 'BINARY_BYTE_SIZE')](https://github.com/jesec/samfirm.js/issues/5)

**Comment by Unknown78** [comment]
@zacharee Could you please help me?

**Comment by zacharee** [comment]
This is on Samsung's end. Try a different CSC.

**Comment by Unknown78** [comment]
@zacharee 

What do you mean by Samsung's end?
This is the latest firmware of that CSC, the issue should be different than https://github.com/zacharee/SamloaderKotlin/issues/10

**Comment by zacharee** [comment]
Samsung sometimes doesn't serve firmware for older devices on certain CSCs and will return error 400. There isn't anything you can do about it except try a different CSC.

**Comment by Unknown78** [comment]
@zacharee 
But it is stated that the release date is 2022-08-19
https://doc.samsungmobile.com/SM-N910C/XEO/doc.html

The device is old, but the firmware is still fresh, how could it be that we can't download it?

**Comment by zacharee** [comment]
You're going to have to ask Samsung's internal engineering department.

**Comment by Unknown78** [comment]
@zacharee How to ask them? Do you have the access to contact them? Will they really give you for free so easily? Have you ever tried it?
