### ISSUE TITLE
Cannot get firmware version for galaxy tab a7 lite "Index 2 out of bounds for length 1"

### ISSUE THREAD

**Issue by coocooguy246** [zacharee/SamloaderKotlin#95]
Attempting to download rom for Galaxy tab A7 lite. Initially tried downloading VZW csc, but saw on the forum that verizon rom cant be downloaded through samsung directly, so i switch to XAA, also tried XAS and XAR but still same error. Changing the model like by removing the U at the end just outputs the accessdenied error so i think my model is correct. 

![image](https://user-images.githubusercontent.com/21000665/230523490-e44d9eb3-b956-4264-ac7d-ffdc576ce98d.png)

**Comment by zacharee** [comment]
Use TMB for the CSC. Unlocked CSCs aren't served for locked (U-only) variants.
